source 'https://rubygems.org'

# Jazzy only loosely pins sqlite, but they bumped their min ruby version to above
# what we support, we we've gotta do this nonsense.
gem 'sqlite3', '1.5.4'
gem 'jazzy', '0.15.3'
gem 'concurrent-ruby', '1.3.4'
