source "git@github.sc-corp.net:Snapchat/camera-kit-ios-pod-repo.git"

target 'CameraKitSample' do
	pod 'CameraKit', '0.4.0'
	pod 'CameraKitReferenceUI', '0.4.0'

	target 'CameraKitSampleTests' do
		inherit! :complete
	end
end